const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Generates a prescription PDF.
 * @param {object} data - The prescription data.
 * @returns {Promise<string>} - The path to the generated PDF.
 */
const generatePrescriptionPDF = async (data) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const filename = `prescription_${data.bookingId}_${Date.now()}.pdf`;
      const outputDir = path.join(__dirname, '../../../public/prescriptions');
      
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }
      
      const outputPath = path.join(outputDir, filename);
      const stream = fs.createWriteStream(outputPath);

      doc.pipe(stream);

      // Header
      doc.fontSize(20).text('AarogyaLink Telemedicine', { align: 'center' });
      doc.fontSize(10).text('District Hospital Consultation', { align: 'center' });
      doc.moveDown();
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
      doc.moveDown();

      // Patient & Doctor Info
      doc.fontSize(12).text(`Patient: ${data.patientName}`);
      doc.text(`Doctor: ${data.doctorName}`);
      doc.text(`Date: ${new Date().toLocaleDateString()}`);
      doc.moveDown();

      // Clinical Brief (AI Generated)
      if (data.symptomBrief) {
        doc.fontSize(14).text('Clinical Brief:', { underline: true });
        doc.fontSize(11).text(data.symptomBrief);
        doc.moveDown();
      }

      // Prescription
      doc.fontSize(14).text('Prescription / Advice:', { underline: true });
      doc.fontSize(12).text(data.prescription);
      doc.moveDown();

      // Footer
      doc.fontSize(10).text('Generated by AarogyaLink Platform', { align: 'center', baseline: 'bottom' });

      doc.end();

      stream.on('finish', () => {
        resolve(outputPath);
      });

      stream.on('error', (err) => {
        reject(err);
      });
    } catch (err) {
      reject(err);
    }
  });
};

module.exports = {
  generatePrescriptionPDF,
};
